# QUIZ 5

Consider an input image with 2 channels:
 $$
 \text{channel 1} = 
 \begin{bmatrix}
 3&2&1\\
 2&1&2\\
 1&2&3  
 \end{bmatrix}
 \qquad  \text{channel 2} = 
 \begin{bmatrix}
 1&2&3\\
 2&1&2\\
 3&2&1
 \end{bmatrix}
 $$
 and a convolutional module with one filter only:
 
 $$
 \text{channel 1} = 
 \begin{bmatrix}
 1&1 \\
 1&1
 \end{bmatrix}
 \qquad 
 \text{ channel 2} = 
 \begin{bmatrix}
 1&0 \\
 1&1
 \end{bmatrix}
 $$
Your goal is to compute the resulting activation map. You are strongly encouraged to check your result with pen and paper.

In [6]:
import torch
import torch.nn as nn

### Make the convolutional module (set bias to False, don't use any padding)

In [7]:
mod = nn.Conv2d(2,1, kernel_size=2, padding=0, bias=False)

### Change the internal parameters of the convolutional module so that they are equal to the  desired filter. Be mindfull of the dimention. Likely you are going to use the functions 
* torch.stack()
* view()
* nn.Parameters()

In [17]:
# filt_ch1 = torch.Tensor([[1,1],[1,1]])
# filt_ch2 = torch.Tensor([[1,0],[1,1]])
# filter_ = nn.Parameter(torch.stack((filt_ch1,filt_ch2), dim=0))

filter_  = nn.Parameter(torch.Tensor([[[[1,1],[1,1]],[[1,0],[1,1]]]]))
print(filter_.size())
mod.weight = filter_
print(mod.weight)

torch.Size([1, 2, 2, 2])
Parameter containing:
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 0.],
          [1., 1.]]]], requires_grad=True)


### Create the input picture:
$$
 \text{channel 1} = 
 \begin{bmatrix}
 3&2&1\\
 2&1&2\\
 1&2&3  
 \end{bmatrix}
 \qquad  \text{channel 2} = 
 \begin{bmatrix}
 1&2&3\\
 2&1&2\\
 3&2&1
 \end{bmatrix}
 $$

In [18]:
ch1 = torch.Tensor([[3,2,1], [2,1,2], [1,2,3]])
ch2 = torch.Tensor([[1,2,3], [2,1,2], [3,2,1]])
img = torch.stack((ch1,ch2), dim=0)
print(img)
print(img.size())

tensor([[[3., 2., 1.],
         [2., 1., 2.],
         [1., 2., 3.]],

        [[1., 2., 3.],
         [2., 1., 2.],
         [3., 2., 1.]]])
torch.Size([2, 3, 3])


### Do the convolution and print the resulting activation map. Don't forget that you need to take care of the batch size: Use the command view()

In [19]:
bs=1
img = img.view(bs,2,3,3)
print(img.size())
act_map = mod(img)
#act_map = mod(img.unsqueeze(0))


torch.Size([1, 2, 3, 3])


In [20]:
print(act_map)

tensor([[[[12., 11.],
          [13., 12.]]]], grad_fn=<ThnnConv2DBackward>)
