### REVISITING THE VIEW COMMAND -- DEMO 

In [1]:
import torch

In [2]:
X=torch.arange(12)

print(X)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


### We can specify only one of the dimension and let pytorch figure out the remaining one

In [3]:
Y = X.view(6,-1)

print(Y)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])


In [4]:
Z = X.view(-1,4)

print(Z)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


### Suppose we have a batch of 2 x 2 matrices

In [5]:
bs=10

X=torch.rand(bs,2,2)

print(X)

tensor([[[0.4176, 0.2763],
         [0.2876, 0.4616]],

        [[0.1990, 0.3635],
         [0.8717, 0.5607]],

        [[0.3499, 0.1369],
         [0.4932, 0.0682]],

        [[0.0998, 0.5990],
         [0.6002, 0.7454]],

        [[0.8956, 0.8345],
         [0.6781, 0.3386]],

        [[0.5394, 0.8195],
         [0.9990, 0.6302]],

        [[0.6813, 0.0775],
         [0.9435, 0.9464]],

        [[0.1015, 0.4515],
         [0.6625, 0.3099]],

        [[0.9654, 0.2896],
         [0.1136, 0.0364]],

        [[0.8077, 0.1572],
         [0.8867, 0.7010]]])


### We can reshape it as a batch of vectors with 4 entries each

In [6]:
Y = X.view(-1,4)

print(Y)

tensor([[0.4176, 0.2763, 0.2876, 0.4616],
        [0.1990, 0.3635, 0.8717, 0.5607],
        [0.3499, 0.1369, 0.4932, 0.0682],
        [0.0998, 0.5990, 0.6002, 0.7454],
        [0.8956, 0.8345, 0.6781, 0.3386],
        [0.5394, 0.8195, 0.9990, 0.6302],
        [0.6813, 0.0775, 0.9435, 0.9464],
        [0.1015, 0.4515, 0.6625, 0.3099],
        [0.9654, 0.2896, 0.1136, 0.0364],
        [0.8077, 0.1572, 0.8867, 0.7010]])
